const zonesData = [
  {
    "name": "Nasr City Free Zone",
    "type": "PFZ",
    "latitude": 30.0626,
    "longitude": 31.3219,
    "color": "blue",
    "operator": "GAFI",
    "totalArea": "756,000",
    "slotsStartFrom": "150 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Media Production City Free Zone",
    "type": "PFZ",
    "latitude": 30.0131,
    "longitude": 31.2089,
    "color": "blue",
    "operator": "GAFI",
    "totalArea": "",
    "slotsStartFrom": "100 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Badr Industrial City",
    "type": "Investment",
    "latitude": 30.1833,
    "longitude": 31.7167,
    "color": "green",
    "operator": "GAFI",
    "totalArea": "",
    "slotsStartFrom": "500 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "15th Of May City Industrial Zone",
    "type": "Investment",
    "latitude": 29.8667,
    "longitude": 31.2833,
    "color": "green",
    "operator": "GAFI",
    "totalArea": "",
    "slotsStartFrom": "500 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Katameya Industrial Zone",
    "type": "Investment",
    "latitude": 29.9833,
    "longitude": 31.4167,
    "color": "green",
    "operator": "GAFI",
    "totalArea": "",
    "slotsStartFrom": "400 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "AL OULA",
    "type": "Private",
    "latitude": 29.5558,
    "longitude": 30.5101,
    "color": "orange",
    "operator": "Elsewedy Development + Al Oula",
    "totalArea": "1,000,000",
    "slotsStartFrom": "5,000 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "INDUSTRIA OCTOBER",
    "type": "Private",
    "latitude": 29.4751,
    "longitude": 30.4322,
    "color": "orange",
    "operator": "Elsewedy Development",
    "totalArea": "2,600,000",
    "slotsStartFrom": "2,500 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "CPC Industrial Park 6th of October",
    "type": "Private",
    "latitude": 29.9502,
    "longitude": 30.8762,
    "color": "orange",
    "operator": "CPC",
    "totalArea": "1,500,000",
    "slotsStartFrom": "2,500 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "IDG e² October",
    "type": "Private",
    "latitude": 29.9167,
    "longitude": 30.8833,
    "color": "orange",
    "operator": "IDG",
    "totalArea": "3,100,000",
    "slotsStartFrom": "2,500 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Polaris International Industrial Park",
    "type": "Private",
    "latitude": 29.9097,
    "longitude": 30.9746,
    "color": "orange",
    "operator": "Polaris Parks",
    "totalArea": "2,000,000",
    "slotsStartFrom": "4,500 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Polaris Al Zamil",
    "type": "Private",
    "latitude": 29.92,
    "longitude": 30.985,
    "color": "orange",
    "operator": "Polaris Parks + Zamil Holding",
    "totalArea": "1,100,000",
    "slotsStartFrom": "4,500 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Polaris New October City",
    "type": "Private",
    "latitude": 29.88,
    "longitude": 30.94,
    "color": "orange",
    "operator": "Polaris Parks",
    "totalArea": "2,600,000",
    "slotsStartFrom": "3,000 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "6th of October Industrial City",
    "type": "Investment",
    "latitude": 29.9097,
    "longitude": 30.9746,
    "color": "green",
    "operator": "GAFI",
    "totalArea": "",
    "slotsStartFrom": "800 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "CPC Industrial Park Sadat City ",
    "type": "Private",
    "latitude": 30.3593,
    "longitude": 30.5327,
    "color": "orange",
    "operator": "CPC",
    "totalArea": "1,100,000",
    "slotsStartFrom": "5,200 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "INDUSTRIA SADAT",
    "type": "Private",
    "latitude": 30.2604,
    "longitude": 30.3601,
    "color": "orange",
    "operator": "Elsewedy Development",
    "totalArea": "1,400,000",
    "slotsStartFrom": "5,000 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Polaris Sadat City Industrial Park",
    "type": "Private",
    "latitude": 30.3833,
    "longitude": 30.4333,
    "color": "orange",
    "operator": "Polaris Parks",
    "totalArea": "1,400,000",
    "slotsStartFrom": "4,500 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Sadat Industrial City",
    "type": "Investment",
    "latitude": 30.3667,
    "longitude": 30.4167,
    "color": "green",
    "operator": "GAFI",
    "totalArea": "",
    "slotsStartFrom": "600 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "INDUSTRIA BORG EL ARAB",
    "type": "Private",
    "latitude": 30.5131,
    "longitude": 29.3733,
    "color": "orange",
    "operator": "Elsewedy Development",
    "totalArea": "1,500,000",
    "slotsStartFrom": "2,500 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Alexandria Free Zone",
    "type": "PFZ",
    "latitude": 31.2001,
    "longitude": 29.9187,
    "color": "blue",
    "operator": "GAFI",
    "totalArea": "5,682,600",
    "slotsStartFrom": "500 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Borg El Arab Industrial City",
    "type": "Investment",
    "latitude": 30.9167,
    "longitude": 29.6333,
    "color": "green",
    "operator": "GAFI",
    "totalArea": "",
    "slotsStartFrom": "700 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Ameriya Industrial Zone",
    "type": "Investment",
    "latitude": 31.0065,
    "longitude": 29.815,
    "color": "green",
    "operator": "GAFI",
    "totalArea": "",
    "slotsStartFrom": "400 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Suez Free Zone",
    "type": "PFZ",
    "latitude": 29.9668,
    "longitude": 32.5498,
    "color": "blue",
    "operator": "GAFI",
    "totalArea": "1,218,000",
    "slotsStartFrom": "600 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Suez Canal Economic Zone",
    "type": "SEZ",
    "latitude": 30.8025,
    "longitude": 32.3,
    "color": "purple",
    "operator": "SCZone Authority",
    "totalArea": "",
    "slotsStartFrom": "5,000 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "SOKHNA360",
    "type": "Private",
    "latitude": 29.4446,
    "longitude": null,
    "color": "orange",
    "operator": "Elsewedy Development",
    "totalArea": "10,000,000",
    "slotsStartFrom": "10,000 sqm",
    "pricePerSqm": "",
    "benefits": "100% Exemption from custom duties & sales tax"
  },
  {
    "name": "INDUSTRIA SOKHNA",
    "type": "Private",
    "latitude": 29.4055,
    "longitude": 32.1827,
    "color": "orange",
    "operator": "Elsewedy Development",
    "totalArea": "1,700,000",
    "slotsStartFrom": "5,000 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Ain Sokhna SEZ",
    "type": "SEZ",
    "latitude": 29.6,
    "longitude": 32.35,
    "color": "purple",
    "operator": "SCZone Authority",
    "totalArea": "",
    "slotsStartFrom": "2,000 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Ismailia Free Zone",
    "type": "PFZ",
    "latitude": 30.5965,
    "longitude": 32.2715,
    "color": "blue",
    "operator": "GAFI",
    "totalArea": "609,000",
    "slotsStartFrom": "200 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Kantara East Industrial Zone",
    "type": "Investment",
    "latitude": 30.8333,
    "longitude": 32.3167,
    "color": "green",
    "operator": "GAFI",
    "totalArea": "",
    "slotsStartFrom": "300 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "IDG East Port Said",
    "type": "Private",
    "latitude": 31.2833,
    "longitude": 32.35,
    "color": "orange",
    "operator": "IDG",
    "totalArea": "16,000,000",
    "slotsStartFrom": "3,000 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Port Said Free Zone",
    "type": "PFZ",
    "latitude": 31.2653,
    "longitude": 32.3019,
    "color": "blue",
    "operator": "GAFI",
    "totalArea": "802,200",
    "slotsStartFrom": "400 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "East Port Said SEZ",
    "type": "SEZ",
    "latitude": 31.2889,
    "longitude": 32.3262,
    "color": "purple",
    "operator": "SCZone Authority",
    "totalArea": "",
    "slotsStartFrom": "3,000 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Dashlut Industrial Zone",
    "type": "Investment",
    "latitude": 27.1833,
    "longitude": 31.1667,
    "color": "green",
    "operator": "GAFI",
    "totalArea": "",
    "slotsStartFrom": "300 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Damietta Free Zone",
    "type": "PFZ",
    "latitude": 31.4165,
    "longitude": 31.8133,
    "color": "blue",
    "operator": "GAFI",
    "totalArea": "",
    "slotsStartFrom": "250 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "New Thebes Industrial Zone",
    "type": "Investment",
    "latitude": 25.6872,
    "longitude": 32.6396,
    "color": "green",
    "operator": "GAFI",
    "totalArea": "",
    "slotsStartFrom": "800 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "IDG e² Alamein",
    "type": "Private",
    "latitude": 30.8333,
    "longitude": 28.95,
    "color": "orange",
    "operator": "IDG",
    "totalArea": "2,700,000",
    "slotsStartFrom": "3,000 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Matahra Industrial Zone",
    "type": "Investment",
    "latitude": 28.1167,
    "longitude": 30.75,
    "color": "green",
    "operator": "GAFI",
    "totalArea": "",
    "slotsStartFrom": "350 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Kalahun Industrial Zone",
    "type": "Investment",
    "latitude": 26.1667,
    "longitude": 32.7167,
    "color": "green",
    "operator": "GAFI",
    "totalArea": "",
    "slotsStartFrom": "400 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "INDUSTRIA ASHER",
    "type": "Private",
    "latitude": 30.1556,
    "longitude": 31.49,
    "color": "orange",
    "operator": "Elsewedy Development",
    "totalArea": "4,000,000",
    "slotsStartFrom": "5,000 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "INDUSTRIA WEST",
    "type": "Private",
    "latitude": 30.3167,
    "longitude": 31.7833,
    "color": "orange",
    "operator": "Elsewedy Development",
    "totalArea": "1,000,000",
    "slotsStartFrom": "7,000 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "INDUSTRIA EAST",
    "type": "Private",
    "latitude": 30.2154,
    "longitude": 31.5,
    "color": "orange",
    "operator": "Elsewedy Development",
    "totalArea": "3,000,000",
    "slotsStartFrom": "3,000 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "10th of Ramadan Industrial City",
    "type": "Investment",
    "latitude": 30.3128,
    "longitude": 31.7421,
    "color": "green",
    "operator": "GAFI",
    "totalArea": "",
    "slotsStartFrom": "1,000 sqm",
    "pricePerSqm": "",
    "benefits": ""
  },
  {
    "name": "Golden Triangle SEZ",
    "type": "SEZ",
    "latitude": 26.8206,
    "longitude": 31.8025,
    "color": "purple",
    "operator": "GAFI",
    "totalArea": "",
    "slotsStartFrom": "10,000 sqm",
    "pricePerSqm": "",
    "benefits": ""
  }
];

if (typeof module !== 'undefined') {
  module.exports = zonesData;
} else {
  window.zonesData = zonesData;
}
